source("scripts/01_crime-data_combine.R")
source("scripts/02_crime-data_cleanse.R")
source("scripts/03_grided-population-data_extract.R")
source("scripts/04_maps_simplify.R")
source("scripts/05_leaflet-data_setup.R")
